spring.datasource.url=jdbc:mysql://localhost:3306/fixit_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Argentina/Cordoba&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080
server.address=0.0.0.0
spring.mvc.pathmatch.use-suffix-pattern=false
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.no-cache=true

# JWT — clave de 256 bits para HS256
fixit.jwt.secret=fixit-secret-key-256bits-para-hs256-tesis-2025-seguro
